Repository metaworking/channeld-ue-plugin, pull requests merged in 2023-08, with the labels that each got.

#55 Add custom StaticMeshComponentReplicator
  Source/ChanneldUE/ChanneldUE.cpp
  Source/ChanneldUE/ChanneldUtils.h
  Source/ChanneldUE/Replication/ChanneldStaticMeshComponentReplicator.cpp
  Source/ChanneldUE/Replication/ChanneldStaticMeshComponentReplicator.h
  Source/ChanneldUE/unreal_common.pb.cpp
  Source/ChanneldUE/unreal_common.pb.h
  Source/ReplicatorGenerator/Private/ReplicatorCodeGenerator.cpp
  Source/ReplicatorGenerator/Public/ReplicatorGeneratorUtils.h
Labels: bug

#59 Add Clang for formatting generated code
  .gitignore
  Source/ChanneldEditor/ChanneldEditor.Build.cs
  Source/ChanneldEditor/ChanneldEditorSubsystem.cpp
  Source/ThirdParty/clang-format.exe
Labels: enhancement, tool

#64 Set the old value to the RepNotify
  Source/ReplicatorGenerator/Private/PropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/ArrayPropertyDecorator.cpp
  Source/ReplicatorGenerator/Public/PropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/ArrayPropertyDecorator.h
Labels: bug

#63 Fix struct declaration problems
  Source/ChanneldUE/Replication/ChanneldPlayerStateReplicator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/ArrayPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/StructPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/ReplicatedActorDecorator.cpp
  Source/ReplicatorGenerator/Private/ReplicatorCodeGenerator.cpp
  Source/ReplicatorGenerator/Public/PropertyDecorator/UnrealObjectPropertyDecorator.h
Labels: bug

#67 Call RepNotify functions at the end of OnStateChanged
  Source/ChanneldUE/Replication/ChanneldActorComponentReplicator.cpp
  Source/ChanneldUE/Replication/ChanneldActorReplicator.cpp
  Source/ChanneldUE/Replication/ChanneldCharacterReplicator.cpp
  Source/ChanneldUE/Replication/ChanneldControllerReplicator.cpp
  Source/ChanneldUE/Replication/ChanneldGameStateBaseReplicator.cpp
  Source/ChanneldUE/Replication/ChanneldGameStateBaseReplicator.h
  Source/ChanneldUE/Replication/ChanneldPawnReplicator.cpp
  Source/ChanneldUE/Replication/ChanneldPlayerStateReplicator.cpp
  Source/ChanneldUE/Replication/ChanneldPlayerStateReplicator.h
  Source/ChanneldUE/Replication/ChanneldReplication.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/ActorCompPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/ArrayPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/NamePropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/StringPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/StructPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/TextPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/UnrealObjectPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/VectorPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/ReplicatedActorDecorator.cpp
  Source/ReplicatorGenerator/Public/PropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/ActorCompPropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/ArrayPropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/NamePropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/RotatorPropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/StringPropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/StructPropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/TextPropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/UnrealObjectPropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/VectorPropertyDecorator.h
Labels: bug

#70 Add dirty flag for array field in generated proto
  Source/ReplicatorGenerator/Private/PropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/ArrayPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/ReplicatedActorDecorator.cpp
  Source/ReplicatorGenerator/Public/PropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/ArrayPropertyDecorator.h
Labels: bug

#58 Asset replication
  Source/ChanneldUE/ChanneldUtils.h
  Source/ReplicatorGenerator/Private/PropertyDecorator/AssetPropertyDecorator.cpp
  Source/ReplicatorGenerator/Private/PropertyDecorator/AssetPropertyDecoratorBuilder.cpp
  Source/ReplicatorGenerator/Private/PropertyDecoratorFactory.cpp
  Source/ReplicatorGenerator/Public/PropertyDecorator/AssetPropertyDecorator.h
  Source/ReplicatorGenerator/Public/PropertyDecorator/AssetPropertyDecoratorBuilder.h
  Source/ReplicatorGenerator/Public/PropertyDecoratorBuilder.h
Labels: enhancement
